### ISSUE TITLE
Installer doesn't run

### ISSUE THREAD

**Issue by SolDev69** [AlphaMode/MinecraftBig3#1]
error when launching built jar
```
JVM info: Azul Systems, Inc. - 21.0.5 - 21.0.5+11-LTS
java.net.preferIPv4Stack=true
Current Time: 03/01/2025 20:33:57
Host: files.minecraftforge.net [172.64.80.1]
Host: maven.minecraftforge.net [172.64.80.1]
Host: libraries.minecraft.net [13.107.246.35]
Host: launchermeta.mojang.com [13.107.246.35]
Host: piston-meta.mojang.com [13.107.246.35]
java.net.UnknownHostException: No such host is known (authserver.mojang.com)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52)
        at java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1211)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1828)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1139)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688)
        at net.minecraftforge.installer.DownloadUtils.getIps(DownloadUtils.java:290)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)
Exception in thread "main"
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "net.minecraftforge.installer.DownloadUtils.getIps(String)" is null
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)```

**Comment by AlphaMode** [comment]
Wisp loader is public it's just not on a maven

**Comment by SolDev69** [comment]
link? can't find it on your github

**Comment by AlphaMode** [comment]
https://github.com/wisp-toolchain/wisp-loader

**Comment by SolDev69** [comment]
Will try compiling this again tomorrow but if it doesn't work can u fix compile issues for r/AntVenom to have a copy that isn't just reposted mcbig1?

**Comment by SolDev69** [comment]
> Will try compiling this again tomorrow but if it doesn't work can u fix compile issues for r/AntVenom to have a copy that isn't just reposted mcbig1?

Ah I never updated this, yea it doesn't work anymore it just crashes with a useless error.

**Comment by SolDev69** [comment]
Gib proper build instructions por favorus

**Comment by AlphaMode** [comment]
sigma

**Comment by SolDev69** [comment]
Just tried finessing mcbig into vanilla neoforged devenv and dumping packages into source to get it to build and I got stuck at tomlj not compiling

**Comment by AlphaMode** [comment]
Just join me in a discord vc or something

**Comment by SolDev69** [comment]
> Just join me in a discord vc or something

Don't have access to discord right now for reasons, even if I could I don't have access to my account right now because 2fa gone so I have to talk with discord support first.

**Comment by SolDev69** [comment]
> Entry wisp.mod.toml is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.7/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

I keep getting this duplicate error, what's the best way to fix this?

**Comment by SolDev69** [comment]
fixed that, stuck at needing "minecraft-1.0" even when using an older version of wisploader

**Comment by SolDev69** [comment]
```
gradlew :mcbig:runClient

> Configure project :
McBig version 3

> Task :mcbig:runClient FAILED
Exception in thread "main" java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.orElseThrow(Optional.java:377)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

[Incubating] Problems report is available at: file:///C:/Users/****/MinecraftBig3/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mcbig:runClient'.
> Process 'command 'C:\Program Files\Zulu\zulu-21\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.12/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 4s
5 actionable tasks: 1 executed, 4 up-to-date
```
erroring here now using cmd

**Comment by SolDev69** [comment]
how do I run this thing without it tripping out

**Comment by SolDev69** [comment]
I got it to run via manually starting it with Start.java, please fix installer

**Comment by SolDev69** [comment]
```
[20:10:44] [Render thread/INFO] [minecraft/ChatComponent]: [System] [CHAT] Teleported Player564 to 2147483647.500000, 74.243413, -405.500000
[20:10:52] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2684ms or 53 ticks behind
[20:10:57] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[20:10:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[i got it working]'/minecraft:overworld
[20:10:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[i got it working]'/minecraft:the_nether
[20:10:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[i got it working]'/minecraft:the_end
[20:11:15] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[20:11:15] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[i got it working]'/minecraft:overworld
[20:11:15] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[i got it working]'/minecraft:the_nether
[20:11:15] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[i got it working]'/minecraft:the_end
[20:11:16] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Player564 lost connection: Disconnected
[20:11:16] [Server thread/INFO] [minecraft/MinecraftServer]: Player564 left the game
[20:11:16] [Server thread/INFO] [minecraft/ServerCommonPacketListenerImpl]: Stopping singleplayer server as player logged out
[20:11:16] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[20:11:16] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[20:11:16] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[20:11:16] [IOWorker-chunk/ERROR] [minecraft/RegionFile]: Chunk [134217747, -40] stream is truncated: expected 7161 but read 4091
[20:11:16] [Server thread/ERROR] [minecraft/ChunkSerializer]: Chunk file at [134217748, -40] is in the wrong location; relocating. (Expected [134217748, -40], got [134217748, -39])
[20:11:16] [IOWorker-chunk/WARN] [minecraft/RegionFile]: Chunk has both internal and external streams
[20:11:16] [IOWorker-chunk/ERROR] [minecraft/RegionFile]: External chunk path .\saves\i got it working\region\c.134217747.-42.mcc is not file
[20:11:16] [IOWorker-chunk/WARN] [minecraft/RegionFile]: Chunk has both internal and external streams
[20:11:16] [IOWorker-chunk/ERROR] [minecraft/RegionFile]: External chunk path .\saves\i got it working\region\c.134217747.-41.mcc is not file
[20:11:16] [IOWorker-chunk/ERROR] [minecraft/RegionFile]: Chunk [134217747, -44] stream is truncated: expected 7161 but read 4091
[20:11:16] [IOWorker-chunk/ERROR] [minecraft/RegionFile]: Chunk [134217747, -43] stream is truncated: expected 7161 but read 4091
[20:11:17] [Server thread/ERROR] [minecraft/ChunkSerializer]: Chunk file at [134217748, -44] is in the wrong location; relocating. (Expected [134217748, -44], got [134217748, -39])
[20:11:17] [Server thread/ERROR] [minecraft/ChunkSerializer]: Chunk file at [134217748, -43] is in the wrong location; relocating. (Expected [134217748, -43], got [134217748, -39])
[20:11:17] [Server thread/ERROR] [minecraft/ChunkSerializer]: Chunk file at [134217748, -42] is in the wrong location; relocating. (Expected [134217748, -42], got [134217748, -39])
[20:11:17] [Server thread/ERROR] [minecraft/ChunkSerializer]: Chunk file at [134217748, -41] is in the wrong location; relocating. (Expected [134217748, -41], got [134217748, -39])
```
is saving being fried a known issue?

**Comment by SolDev69** [comment]
![image](https://github.com/user-attachments/assets/dc6d0f88-bf2e-419c-9b78-077575cda7d1)
:)

**Comment by SolDev69** [comment]
can I make a post about this on r/AntVenom?

**Comment by SolDev69** [comment]
attempting to pass 2^63 causes this error
`java.lang.IllegalStateException: No chunk holder after ticket has been added: [576460752303423487, -7]`
iirc u fixed this in mcbig 1

**Comment by SolDev69** [comment]
updated issue

**Comment by SolDev69** [comment]
![Image](https://github.com/user-attachments/assets/078b3d8e-9204-4fa2-b34c-d0fa1f2444bb)

@AlphaMode wtf??

**Comment by AlphaMode** [comment]
What

**Comment by AlphaMode** [comment]
I'm just gonna close this for now because I don't have plans for working on this for a while. Not sure what's going on, but I'm going to go ahead and lock this issue,l to avoid things becoming toxic
